# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-06 18:15
from __future__ import unicode_literals

import DjangoUeditor.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_auto_20161210_2353'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='文章标题')),
                ('author', models.CharField(max_length=50, verbose_name='编辑')),
                ('detail', DjangoUeditor.models.UEditorField(default='', verbose_name='文章内容')),
                ('tag', models.CharField(default='', max_length=10, verbose_name='文章标签')),
                ('click_nums', models.IntegerField(default=0, verbose_name='点击数')),
                ('fav_nums', models.IntegerField(default=0, verbose_name='收藏数')),
                ('image', models.ImageField(upload_to='org/%Y/%m', verbose_name='logo')),
                ('url', models.CharField(default='', max_length=10, verbose_name='文章跳转地址')),
                ('index', models.CharField(default='', max_length=10, verbose_name='文章排序')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
            },
        ),
        migrations.RemoveField(
            model_name='courseorg',
            name='city',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='org',
        ),
        migrations.DeleteModel(
            name='CityDict',
        ),
        migrations.DeleteModel(
            name='CourseOrg',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
