# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-12 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_auto_20180506_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.CharField(max_length=100, verbose_name='编辑'),
        ),
        migrations.AlterField(
            model_name='article',
            name='index',
            field=models.CharField(default='', max_length=100, verbose_name='文章排序'),
        ),
        migrations.AlterField(
            model_name='article',
            name='tag',
            field=models.CharField(default='', max_length=100, verbose_name='文章标签'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=100, verbose_name='文章标题'),
        ),
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.CharField(default='', max_length=300, verbose_name='文章跳转地址'),
        ),
    ]
