# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-12 17:19
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0010_auto_20180512_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='detail',
            field=DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='文章内容'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, upload_to='org/%Y/%m', verbose_name='logo'),
        ),
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='文章跳转地址'),
        ),
    ]
