# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-09 16:40
from __future__ import unicode_literals

import DjangoUeditor.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0013_auto_20180520_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='AwardIterm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award_id', models.IntegerField(default=0, verbose_name='关联的金蜘蛛奖id')),
                ('award_sort_id', models.IntegerField(default=0, verbose_name='关联的金蜘蛛奖奖项id')),
                ('title', models.CharField(max_length=100, verbose_name='作品标题')),
                ('image', models.ImageField(blank=True, upload_to='org/%Y/%m', verbose_name='作品图片')),
                ('fav_nums', models.IntegerField(default=0, verbose_name='投票数')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': '金蜘蛛奖参选作品',
                'verbose_name_plural': '金蜘蛛奖参选作品',
            },
        ),
        migrations.CreateModel(
            name='AwardSort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award_id', models.IntegerField(default=0, verbose_name='关联的金蜘蛛奖id')),
                ('title', models.CharField(max_length=100, verbose_name='奖项名称')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': '金蜘蛛奖奖项',
                'verbose_name_plural': '金蜘蛛奖奖项',
            },
        ),
        migrations.CreateModel(
            name='GoldenSpiderAward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('sponsor', models.CharField(max_length=100, verbose_name='主办方')),
                ('co_sponsor', models.CharField(max_length=100, verbose_name='协办方')),
                ('date', models.CharField(max_length=100, verbose_name='举办日期')),
                ('address', models.CharField(max_length=300, verbose_name='举办地址')),
                ('intro', DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='奖项介绍')),
                ('specialists', models.ImageField(blank=True, upload_to='org/%Y/%m', verbose_name='专家评审团')),
                ('process', models.ImageField(blank=True, upload_to='org/%Y/%m', verbose_name='评选流程')),
                ('co_companies', models.ImageField(blank=True, upload_to='org/%Y/%m', verbose_name='战略合作单位')),
                ('platforms', models.ImageField(blank=True, upload_to='org/%Y/%m', verbose_name='战略合作平台')),
                ('media_orgs', models.ImageField(blank=True, upload_to='org/%Y/%m', verbose_name='媒体支持')),
                ('shoot_orgs', models.ImageField(blank=True, upload_to='org/%Y/%m', verbose_name='指定拍摄机构')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': '金蜘蛛奖',
                'verbose_name_plural': '金蜘蛛奖',
            },
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': '资讯', 'verbose_name_plural': '资讯'},
        ),
        migrations.AddField(
            model_name='article',
            name='award_id',
            field=models.IntegerField(default=0, verbose_name='关联的金蜘蛛奖id'),
        ),
    ]
