# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-09 16:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0014_auto_20180609_1640'),
    ]

    operations = [

        migrations.AddField(
            model_name='article',
            name='award',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.GoldenSpiderAward', verbose_name='关联的金蜘蛛奖id'),
        ),
        migrations.AlterField(
            model_name='goldenspideraward',
            name='co_companies',
            field=models.CharField(max_length=1000, verbose_name='战略合作单位'),
        ),
    ]
