# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-09 17:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0016_auto_20180609_1700'),
    ]

    operations = [
    ]
