# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-09 17:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0017_auto_20180609_1709'),
    ]

    operations = [

        migrations.AlterField(
            model_name='article',
            name='award',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='article.GoldenSpiderAward', verbose_name='关联的金蜘蛛奖id'),
        ),
    ]
