# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-09 17:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0019_remove_article_award_id'),
    ]

    operations = [

    ]
