# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-09 18:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0021_auto_20180609_1750'),
    ]

    operations = [

        migrations.AddField(
            model_name='awarditerm',
            name='golden_spider_award',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='article.GoldenSpiderAward', verbose_name='关联的金蜘蛛奖id'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='awardsort',
            name='golden_spider_award',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='article.GoldenSpiderAward', verbose_name='关联的金蜘蛛奖id'),
        ),
        migrations.AlterField(
            model_name='awarditerm',
            name='award_sort_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='article.AwardSort', verbose_name='关联的奖项id'),
        ),
    ]
