# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-11 00:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0022_auto_20180609_1813'),
    ]

    operations = [

    ]
