# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-21 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0023_auto_20180611_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='goldenspideraward',
            name='background_img',
            field=models.ImageField(blank=True, upload_to='org/%Y/%m', verbose_name='金蜘蛛背景图'),
        ),
    ]
